### ISSUE TITLE
Unexpected codec:

### ISSUE THREAD

**Issue by kenneththorman** [kenneththorman/appspotdemo-mono#2]
WebRtc VoiceEngine codecs:
12-26 12:47:51.646 I/libjingle(20322): WebRtc VoiceEngine codecs:
12-26 12:47:51.646 I/libjingle(20322): ISAC/16000/1 (103)
12-26 12:47:51.646 I/libjingle(20322): PCMU/8000/1 (0)
12-26 12:47:51.646 I/libjingle(20322): PCMA/8000/1 (8)
12-26 12:47:51.646 W/libjingle(20322): Warning(webrtcvoiceengine.cc:473): Unexpected codec: PCMU/8000/2 (110)
12-26 12:47:51.651 W/libjingle(20322): Warning(webrtcvoiceengine.cc:473): Unexpected codec: PCMA/8000/2 (118)
12-26 12:47:51.651 I/libjingle(20322): ILBC/8000/1 (102)
12-26 12:47:51.651 I/libjingle(20322): G722/16000/1 (9)
12-26 12:47:51.651 W/libjingle(20322): Warning(webrtcvoiceengine.cc:473): Unexpected codec: G722/16000/2 (119)
12-26 12:47:51.651 I/libjingle(20322): opus/48000/2 (111)
ISAC/16000/1 (103)
PCMU/8000/1 (0)
PCMA/8000/1 (8)
Warning(webrtcvoiceengine.cc:473): Unexpected codec: PCMU/8000/2 (110)
Warning(webrtcvoiceengine.cc:473): Unexpected codec: PCMA/8000/2 (118)
ILBC/8000/1 (102)
G722/16000/1 (9)
Warning(webrtcvoiceengine.cc:473): Unexpected codec: G722/16000/2 (119)
opus/48000/2 (111)
CN/8000/1 (13)
CN/16000/1 (105)
CN/32000/1 (106)
telephone-event/8000/1 (126)
red/8000/1 (127)
WebRtcVideoEngine::WebRtcVideoEngine
WebRtcVoiceEngine::Init

**Comment by ifree** [comment]
Hi, 
I met the same problem. It seems that you have solve it, can you share your solutions?
thanks

**Comment by kenneththorman** [comment]
Hi ifree

I am sorry for the late response, I have been away on holiday. To be honest, I do not remember, the code was still in a very early/fluid state and I was trying to just fix compiler errors, so I was doing multiple things per commit (which is bad for tracking purposes). 

I am not sure if you are using this code I have posted here or if you have the same problem in another codebase, the best suggestion I can give is to try to track it down based on the reporting date of the original issue, the closing date and the commits in between these 2 dates.

I am sorry that I cannot pin point it more specific.

Good luck.

Regards
Kenneth Thorman
